[package]
name = "rpill_lib"
version = "0.1.0"
authors = ["gpestana <g6pestana@gmail.com>"]
edition = "2018"

[dependencies]
mac_address = "1.1.1"
wmi = "0.4"
serde = "1.0.117"
serde_json = "1.0.59"
libc = "0.2"
